export interface PortfolioItem {
  id: number;
  image: string;
  title: string;
  category: string;
  description: string;
  metrics?: {
    before: string;
    after: string;
  };
  width: number;
  height: number;
}

// Mock portfolio data - replace with real images
export const portfolioItems: PortfolioItem[] = [
  {
    id: 1,
    image: "/assets/homepage/portfolio/product-image1.png",
    title: "Premium Kitchen Knife Set",
    category: "Product Photography",
    description:
      "Complete listing redesign with lifestyle photography and A+ content optimization.",
    metrics: { before: "3.2% CVR", after: "7.8% CVR" },
    width: 800,
    height: 1000,
  },
  {
    id: 2,
    image: "/assets/homepage/portfolio/product-image2.png",
    title: "Ergonomic Office Chair",
    category: "Lifestyle Photography",
    description:
      "Studio and lifestyle shots showcasing comfort and features.",
    metrics: { before: "4.1% CVR", after: "9.2% CVR" },
    width: 800,
    height: 600,
  },
  {
    id: 3,
    image: "/assets/homepage/portfolio/a-plus-content.png",
    title: "Wireless Earbuds A+ Content",
    category: "A+ Content",
    description: "Premium A+ content design with infographics and comparisons.",
    metrics: { before: "5.5% CVR", after: "12.1% CVR" },
    width: 1200,
    height: 800,
  },
  {
    id: 4,
    image: "/assets/homepage/hero/header-bg.png",
    title: "Smart Home Security Camera",
    category: "Product Photography",
    description: "Technical product shots with feature callouts.",
    metrics: { before: "2.8% CVR", after: "6.9% CVR" },
    width: 800,
    height: 1200,
  },
  {
    id: 5,
    image: "/assets/homepage/portfolio/product-image1.png",
    title: "Fitness Resistance Bands",
    category: "Lifestyle Photography",
    description: "Action shots demonstrating product use cases.",
    metrics: { before: "3.9% CVR", after: "8.4% CVR" },
    width: 800,
    height: 900,
  },
  {
    id: 6,
    image: "/assets/homepage/portfolio/product-image2.png",
    title: "Stainless Steel Water Bottle",
    category: "Product Photography",
    description: "Clean product shots with lifestyle context.",
    metrics: { before: "4.2% CVR", after: "9.8% CVR" },
    width: 800,
    height: 1100,
  },
  {
    id: 7,
    image: "/assets/homepage/hero/header-bg-c.png",
    title: "Pet Grooming Kit",
    category: "Lifestyle Photography",
    description: "Before/after shots with happy pet owners.",
    metrics: { before: "3.5% CVR", after: "7.6% CVR" },
    width: 800,
    height: 700,
  },
  {
    id: 8,
    image: "/assets/homepage/portfolio/a-plus-content.png",
    title: "Yoga Mat Premium Listing",
    category: "A+ Content",
    description: "Full listing optimization with comparison charts.",
    metrics: { before: "5.1% CVR", after: "11.3% CVR" },
    width: 1200,
    height: 900,
  },
  {
    id: 9,
    image: "/assets/homepage/portfolio/product-image1.png",
    title: "LED Desk Lamp",
    category: "Product Photography",
    description: "Technical and lifestyle shots in various settings.",
    metrics: { before: "3.3% CVR", after: "7.2% CVR" },
    width: 800,
    height: 1000,
  },
  {
    id: 10,
    image: "/assets/homepage/portfolio/product-image2.png",
    title: "Organic Skincare Set",
    category: "Lifestyle Photography",
    description: "Premium beauty photography with ingredient highlights.",
    metrics: { before: "4.8% CVR", after: "10.5% CVR" },
    width: 800,
    height: 800,
  },
  {
    id: 11,
    image: "/assets/homepage/hero/header-bg.png",
    title: "Bluetooth Speaker",
    category: "Product Photography",
    description: "Dynamic product shots showcasing design and portability.",
    metrics: { before: "3.7% CVR", after: "8.1% CVR" },
    width: 800,
    height: 950,
  },
  {
    id: 12,
    image: "/assets/homepage/portfolio/a-plus-content.png",
    title: "Coffee Maker A+ Redesign",
    category: "A+ Content",
    description: "Complete brand story with feature comparisons.",
    metrics: { before: "5.8% CVR", after: "13.2% CVR" },
    width: 1200,
    height: 850,
  },
  {
    id: 13,
    image: "/assets/homepage/portfolio/product-image1.png",
    title: "Travel Backpack",
    category: "Lifestyle Photography",
    description: "Adventure photography showcasing capacity and features.",
    metrics: { before: "4.0% CVR", after: "9.1% CVR" },
    width: 800,
    height: 1050,
  },
  {
    id: 14,
    image: "/assets/homepage/portfolio/product-image2.png",
    title: "Smart Watch",
    category: "Product Photography",
    description: "High-tech product shots with UI mockups.",
    metrics: { before: "3.1% CVR", after: "7.4% CVR" },
    width: 800,
    height: 900,
  },
  {
    id: 15,
    image: "/assets/homepage/hero/header-bg-c.png",
    title: "Kitchen Blender",
    category: "Lifestyle Photography",
    description: "Action shots creating smoothies and recipes.",
    metrics: { before: "4.4% CVR", after: "9.6% CVR" },
    width: 800,
    height: 1100,
  },
  {
    id: 16,
    image: "/assets/homepage/portfolio/a-plus-content.png",
    title: "Gaming Mouse A+ Content",
    category: "A+ Content",
    description: "Technical specs with gaming lifestyle imagery.",
    metrics: { before: "6.2% CVR", after: "14.1% CVR" },
    width: 1200,
    height: 800,
  },
  {
    id: 17,
    image: "/assets/homepage/portfolio/product-image1.png",
    title: "Baby Monitor",
    category: "Product Photography",
    description: "Lifestyle and technical shots for peace of mind.",
    metrics: { before: "3.6% CVR", after: "8.3% CVR" },
    width: 800,
    height: 950,
  },
  {
    id: 18,
    image: "/assets/homepage/portfolio/product-image2.png",
    title: "Electric Toothbrush",
    category: "Lifestyle Photography",
    description: "Clean, medical-grade photography with family context.",
    metrics: { before: "4.7% CVR", after: "10.2% CVR" },
    width: 800,
    height: 850,
  },
  {
    id: 19,
    image: "/assets/homepage/hero/header-bg.png",
    title: "Camping Tent",
    category: "Lifestyle Photography",
    description: "Outdoor adventure photography in natural settings.",
    metrics: { before: "3.8% CVR", after: "8.7% CVR" },
    width: 800,
    height: 1000,
  },
  {
    id: 20,
    image: "/assets/homepage/portfolio/a-plus-content.png",
    title: "Vitamin Supplement Brand Store",
    category: "A+ Content",
    description: "Complete brand story with scientific backing.",
    metrics: { before: "5.4% CVR", after: "12.8% CVR" },
    width: 1200,
    height: 900,
  },
  // Additional items for infinite scroll
  {
    id: 21,
    image: "/assets/homepage/portfolio/product-image1.png",
    title: "Leather Wallet",
    category: "Product Photography",
    description: "Premium leather goods photography with detail shots.",
    metrics: { before: "4.3% CVR", after: "9.5% CVR" },
    width: 800,
    height: 700,
  },
  {
    id: 22,
    image: "/assets/homepage/portfolio/product-image2.png",
    title: "Air Purifier",
    category: "Product Photography",
    description: "Clean room photography with air quality graphics.",
    metrics: { before: "3.4% CVR", after: "7.9% CVR" },
    width: 800,
    height: 1050,
  },
  {
    id: 23,
    image: "/assets/homepage/hero/header-bg-c.png",
    title: "Dog Training Collar",
    category: "Lifestyle Photography",
    description: "Happy pet training scenarios with owners.",
    metrics: { before: "4.6% CVR", after: "10.1% CVR" },
    width: 800,
    height: 900,
  },
  {
    id: 24,
    image: "/assets/homepage/portfolio/a-plus-content.png",
    title: "Protein Powder A+ Content",
    category: "A+ Content",
    description: "Fitness lifestyle with nutritional breakdown.",
    metrics: { before: "6.0% CVR", after: "13.5% CVR" },
    width: 1200,
    height: 850,
  },
];

export const categories = [
  "All",
  "Product Photography",
  "Lifestyle Photography",
  "A+ Content",
];
